version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce_network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migration:
    build:
      context: .
      dockerfile: scripts/Dockerfile.migration
    container_name: ecommerce-migration
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - ecommerce_network

  app:
    build:
      context: .
    container_name: ecommerce-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - ecommerce_network
    restart: unless-stopped

networks:
  ecommerce_network:

volumes:
  mongodb_data:
